version: '3.3'

services:
  app:
    image: "next-app"
    container_name: "next-app"
    networks:
      - server
    ports:
      - 4400:4400
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
networks:
  server:
